from django.urls import path, include
from . import views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('expenses/', views.ExpenseListView.as_view(), name='expense-all'),
    path('expense/<int:pk>', views.ExpenseDetailView.as_view(), name='expense-one'),
    path('allincome/', views.get_income, name='income-all'),
    path('income/<int:income_id>', views.get_single_income, name='income-one'),
    path('bills/', views.BillListView.as_view(), name='bill-all'),
    path('bill/<uuid:pk>', views.BillDetailView.as_view(), name='bill-one'),
    path('search/', views.search, name='search'),
    path('register/', views.register_user, name='register-url'),
    path('profile/', views.profile, name='profile-url'),
    path('allincome/new', views.IncomeCreateView.as_view(), name='income-new'),
    path('expenses/new', views.ExpenseCreateView.as_view(), name='expense-new'),
    path('bills/new', views.BillCreateView.as_view(), name='bill-new'),
    path('allincome/delete/<int:pk>', views.IncomeDeleteView.as_view(), name='income-delete'),
    path('allincome/update/<int:pk>', views.IncomeUpdateView.as_view(), name='income-update'),
    path('expenses/delete/<int:pk>', views.ExpenseDeleteView.as_view(), name='expense-delete'),
    path('expenses/update/<int:pk>', views.ExpenseUpdateView.as_view(), name='expense-update'),
    path('bills/delete/<uuid:pk>', views.BillDeleteView.as_view(), name='bill-delete'),
    path('bills/update/<uuid:pk>', views.BillUpdateView.as_view(), name='bill-update'),
    path('statisticsincome/', views.income_graph_view, name='statistics-income'),
    path('statisticsincome/monthly', views.income_graph_view_monthly, name='statistics-income-monthly'),
    path('statisticsincome/c1', views.income_graph_view_c1, name='statistics-income-c1'),
    path('statisticsincome/c2', views.income_graph_view_c2, name='statistics-income-c2'),
    path('statisticsincome/c3', views.income_graph_view_c3, name='statistics-income-c3'),
    path('statisticsincome/c4', views.income_graph_view_c4, name='statistics-income-c4'),
    path('statisticsexpense/', views.expenses_graph_view, name='statistics-expenses'),
    path('statisticsexpense/monthly', views.expenses_graph_view_monthly, name='statistics-expenses-monthly'),
    path('statisticsexpense/c1', views.expenses_graph_view_c1, name='statistics-expenses-c1'),
    path('statisticsexpense/c2', views.expenses_graph_view_c2, name='statistics-expenses-c2'),
    path('statisticsexpense/c3', views.expenses_graph_view_c3, name='statistics-expenses-c3'),
    path('statisticsexpense/c4', views.expenses_graph_view_c4, name='statistics-expenses-c4'),
    path('statisticsexpense/c5', views.expenses_graph_view_c5, name='statistics-expenses-c5'),
    path('statisticsbill/', views.bills_scatter_view, name='statistics-bills'),
    path('statisticsbill/c1', views.bills_scatter_view_c1, name='statistics-bill-c1'),
    path('statisticsbill/c2', views.bills_scatter_view_c2, name='statistics-bill-c2'),
    path('statisticsbill/c3', views.bills_scatter_view_c3, name='statistics-bill-c3'),
    path('statisticsbill/monthly', views.bills_scatter_view_monthly, name='statistics-bills-monthly'),
    path('reviews/', views.AppReviewListView.as_view(), name='reviews'),
    path('allincome/new/newcategory', views.IncomeCategoryModeratorCreateView.as_view(), name='income-category-new'),
    path('expenses/new/newcategory', views.ExpenseCategoryModeratorCreateView.as_view(), name='expense-category-new'),
    path('expenses/new/newcompany', views.CompanyModeratorCreateView.as_view(), name='expense-company-new'),
    path('bills/new/newcategory', views.BillCategoryModeratorCreateView.as_view(), name='bill-category-new'),
    path('bills/new/newissuer', views.BillIssuerModeratorCreateView.as_view(), name='bill-issuer-new'),
]
