# Generated by Django 4.2.13 on 2024-05-31 15:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Expense category',
                'verbose_name_plural': 'Expense categories',
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Income category',
                'verbose_name_plural': 'Income categories',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('note', tinymce.models.HTMLField()),
                ('income_category', models.ManyToManyField(to='financeapp.expensecategory')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income',
                'ordering': ('date', 'amount'),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('note', tinymce.models.HTMLField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='pics', verbose_name='Invoice')),
                ('expense_category', models.ManyToManyField(to='financeapp.expensecategory')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ('date', 'amount'),
            },
        ),
    ]
