# Generated by Django 4.2.13 on 2024-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_category',
            field=models.ManyToManyField(to='financeapp.incomecategory'),
        ),
    ]
