# Generated by Django 4.2.13 on 2024-05-31 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_alter_income_income_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='income_category',
        ),
        migrations.AddField(
            model_name='income',
            name='income_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.incomecategory'),
        ),
    ]
