# Generated by Django 4.2.13 on 2024-06-01 08:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_remove_income_income_category_income_income_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('date', 'amount')},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={},
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('billing_date', models.DateField(verbose_name='Billing date')),
                ('date_due', models.DateField(verbose_name='Date due')),
                ('note', tinymce.models.HTMLField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='pics', verbose_name='Bill')),
                ('status', models.CharField(blank=True, choices=[('u', 'Unpaid'), ('p', 'Paid on time'), ('o', 'Overdue'), ('l', 'Paid late')], default='u', help_text='Bill status', max_length=1)),
                ('bill_issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.billissuer')),
            ],
        ),
    ]
