# Generated by Django 4.2.13 on 2024-06-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0005_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillIssuer',
        ),
    ]
