# Generated by Django 4.2.13 on 2024-06-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0007_billissuer_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billissuer',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
    ]
