# Generated by Django 4.2.13 on 2024-06-01 08:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0008_alter_billissuer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='note',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
