# Generated by Django 4.2.13 on 2024-06-01 08:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0009_alter_bill_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='note',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
