# Generated by Django 4.2.13 on 2024-06-01 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0010_alter_expense_note_alter_income_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Bill category',
                'verbose_name_plural': 'Bill categories',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeapp.billcategory'),
        ),
    ]
