# Generated by Django 4.2.13 on 2024-06-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0013_company_expense_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
